discord_api_key = "" # Your bot api key
bot_owner_ids = []   # The IDs of the owner
command_prefix = "!" # The prefix to trigger commands despite slash commands

[logging]
formatter = "%(asctime)s - %(levelname)s - %(module)s - %(message)s"
level = "WARNING"
